labels = {
    'MAGA': 'Republican',
    'AMERICA FIRST': 'Republican',
    'Democrat': 'Democrat',
    'Liberal Democrat': 'Democrat',
    'Republican': 'Republican',
    'Liberal': 'Democrat',
    'Conservative': 'Republican',
    'Reagan Conservative': 'Republican',
    'Goldwater Conservative': 'Republican',
    'Constitutional Conservative': 'Republican',
    'Moderate Conservative': 'Republican',
    'Fiscal Conservative': 'Republican',
    'Bernie Squad - Cadet': 'Democrat',
    'Left': 'Democrat',
    'LibLeft': 'Democrat',
    'Right': 'Republican',
    'AuthRight': 'Republican',
    'WASP Conservative': 'Republican',
    '2A Conservative': 'Republican',
    'Amy Klobuchar for Joe': 'Democrat',
    'Bernie Sanders for Joe': 'Democrat',
    'Andrew Yang for Joe': 'Democrat',
    'Elizabeth Warren for Joe': 'Democrat',
    'Beat Trump': 'Democrat',
    'Barack Obama': 'Democrat',
    'Bill Clinton': 'Democrat',
    'Democratic Party': 'Democrat',
    'Progressive Alliance': 'Democrat',
    'Liberal International': 'Democrat',
    'Pro Life Republican': 'Republican',
    'Pro Life Christian': 'Republican',
    'Filthy Statist': 'Democrat',
    'Neoconservative': 'Republican',
    'I voted for Ronald Reagan': 'Republican',
    'BJP 🌷': 'Republican',  # Right wing party in India...
    'BJP': 'Republican'
}
