top_100_subreddits = {
    'announcements', 'funny', 'AskReddit', 'gaming', 'aww', 'Music', 'pics', 'science', 'worldnews', 'todayilearned',
    'videos', 'movies', 'news', 'Showerthoughts', 'EarthPorn', 'IAmA', 'food', 'gifs', 'askscience', 'Jokes',
    'LifeProTips', 'explainlikeimfive', 'books', 'nottheonion', 'Art', 'DIY', 'mildlyinteresting', 'sports', 'space',
    'gadgets', 'blog', 'Documentaries', 'photoshopbattles', 'GetMotivated', 'tifu', 'UpliftingNews', 'listentothis',
    'television', 'dataisbeautiful', 'history', 'philosophy', 'InternetIsBeautiful', 'memes', 'Futurology',
    'WritingPrompts', 'OldSchoolCool', 'nosleep', 'personalfinance', 'creepy', 'TwoXChromosomes', 'technology',
    'wallstreetbets', 'AdviceAnimals', 'wholesomememes', 'Fitness', 'interestingasfuck', 'politics', 'WTF', 'travel',
    'oddlysatisfying', 'BlackPeopleTwitter', 'bestof', 'lifehacks', 'facepalm', 'leagueoflegends', 'Minecraft',
    'relationship_advice', 'pcmasterrace', 'me_irl', 'Whatcouldgowrong', 'dankmemes', 'NatureIsFuckingLit', 'Tinder',
    'PS4', 'nextfuckinglevel', 'AnimalsBeingBros', 'dadjokes', 'tattoos', 'photography', 'trippinthroughtime',
    'BikiniBottomTwitter', 'nba', 'AnimalsBeingJerks', 'buildapc', 'Unexpected', 'FoodPorn', 'woahdude',
    'instant_regret', 'reactiongifs', 'gardening', 'Overwatch', 'PewdiepieSubmissions', 'AnimalsBeingDerps',
    'boardgames', 'Damnthatsinteresting', 'programming', 'WatchPeopleDieInside', 'pokemon', 'ContagiousLaughter',
    'mildlyinfuriating'
}

political_subreddits = {
    'r/alltheleft',
    'r/Capitalism',
    'r/Conservative',
    'r/conservatives',
    'r/demsocialist',
    'r/democrats',
    'r/GreenParty',
    'r/Liberal',
    'r/Libertarian',
    'r/LibertarianLeft',
    'r/LibertarianSocialism',
    'r/Marxism',
    'r/neoprogs',
    'r/new_right',
    'r/progressive',
    'r/Republican',
    'r/republicanism',
    'r/republicans',
    'r/socialdemocracy',
    'r/socialism',
    'r/tea_party',
    'r/occupywallstreet',
    'r/hillaryclinton'
}
